In [3]:
import pandas as pd

In [5]:
df=pd.read_csv(r'C:\Users\MEGHANA\Desktop\Data Science Projects Ineuorn\New folder\notebooks\data\finalTrain.csv')
df.head()

,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min)
0,0xcdcd,DEHRES17DEL01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,12-02-2022,21:55,22:10,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,0xd987,KOCRES16DEL01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,13-02-2022,14:55,15:05,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,0x2784,PUNERES13DEL03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,04-03-2022,17:30,17:40,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,0xc8b6,LUDHRES15DEL02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,13-02-2022,09:20,09:30,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,0xdb64,KNPRES14DEL02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,14-02-2022,19:50,20:05,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41

In [7]:
df=df.drop(labels=['ID','Delivery_person_ID'],axis=1)

In [9]:
## Independent and dependent features
X = df.drop(labels=['Time_taken (min)'],axis=1)
Y = df[['Time_taken (min)']]

In [10]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [11]:
#define the custom ranking for each ordinal variable
Weather_conditions={'Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny'}
Road_traffic_density={'Jam','High','Medium','Low'}
Type_of_order={'Snack','Meal','Drinks','Buffet'}
Type_of_vehicle={'motorcycle','scooter','electric_scooter','bicycle'}
Festival={'Yes','No'}
City={'Metropolitian','Urban','Semi-Urban'}

In [12]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import make_column_transformer

In [14]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[Weather_conditions,Road_traffic_density,Type_of_order,Type_of_vehicle,Festival,City])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=make_column_transformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [15]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [16]:
X_train=preprocessor.fit_transform(X_train)
X_test=preprocessor.transform(X_test)

TypeError: All estimators should implement fit and transform, or can be 'drop' or 'passthrough' specifiers. '('num_pipeline', Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', StandardScaler())]), Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Vehicle_condition',
       'multiple_deliveries'],
      dtype='object'))' (type <class 'tuple'>) doesn't.

In [17]:
X_train

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City
5755,36.0,4.1,22.310329,73.169083,22.380329,73.239083,02-03-2022,21:40,21:50,Sandstorms,Jam,0,Buffet,motorcycle,0.0,No,Metropolitian
9163,29.0,3.6,22.310526,73.170937,22.370526,73.230937,19-03-2022,21:10,21:15,Sunny,Jam,0,Buffet,motorcycle,3.0,Yes,Urban
16410,31.0,4.8,26.473698,80.352677,26.493698,80.372677,15-02-2022,10:45,10:55,Windy,Low,2,Meal,scooter,1.0,No,Metropolitian
36945,33.0,4.2,15.157944,73.950889,15.287944,74.080889,14-02-2022,19:15,19:30,Windy,Jam,2,Meal,scooter,1.0,No,Metropolitian
14679,34.0,4.1,19.126630,72.829976,19.146630,72.849976,09-03-2022,08:45,0.375,Windy,Low,0,Meal,motorcycle,1.0,No,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919,37.0,4.9,26.474986,80.342796,26.494986,80.362796,17-02-2022,08:25,08:35,Sunny,Low,1,Snack,motorcycle,0.0,No,Urban
33268,28.0,4.9,17.431477,78.400350,17.481477,78.450350,01-04-2022,17:40,17:45,Fog,Medium,2,Buffet,motorcycle,0.0,No,Metropolitian
44845,20.0,NaN,22.514585,88.393310,22.594585,88.473310,14-02-2022,22:20,22:25,Fog,Low,2,Drinks,scooter,1.0,No,Metropolitian
4517,34.0,4.6,12.970324,77.645748,12.990324,77.665748,03-04-2022,08:55,09:10,Cloudy,Low,1,Buffet,motorcycle,NaN,No,Metropolitian
38693,22.0,4.7,13.058616,80.264151,13.108616,80.314151,13-03-2022,19:50,19:55,Windy,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian